language: node_js
node_js:
- '6'
- '10'
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libcairo2-dev
    - libgif-dev
    - graphicsmagick
    - libjpeg8-dev
before_script:
- npm install -g grunt-cli
env:
- CXX=g++-4.8
deploy:
  provider: npm
  email: vilson@void.cc
  api_key:
    secure: KLsA9Ct3N8JF0KdxSF2PCbnL1GW2+A31f5A85LxuE3YEJUiRu03v6NDklBBRX2EMYppG7vm2h30wojblFi5jbfa/wW0lzeAG0or+jQBjsyuJ0hAGOygW/e+83gI57AweBtJpZ5C2CvpACVX2DntYHPmjXyObTEsCSuRvEaBRA5w=
  on:
    tags: true
    repo: noflo/noflo-image
